logging:
  level:
    com: DEBUG
    root: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

management.endpoints.web.exposure.include: info,health,httptrace

# Fixes Caused by: java.sql.SQLFeatureNotSupportedException:
# Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true

spring.liquibase.change-log: classpath:/db/changelog/db.changelog-master.xml

spring.datasource:
  url: jdbc:postgresql://localhost:5432/motive
  username: postgres
  password: postgres

spring.security.oauth2.client.registration.facebook:
  client-id: 2126656117583758
  client-secret: 16d922eb48ba0d30f0d9feee7c1acbec

authentication.success.url: http://localhost:3000

logging.level.org.springframework.security: DEBUG