spring.application.name: 'Milestone Back End'

spring.profiles.active: 'prod'

logging:
  level:
    com: INFO
    root: INFO
    springframework.security: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO

management.endpoints.web.exposure.include: info,health,httptrace

spring.jpa.show-sql: false
spring.jpa.properties.hibernate.format_sql: false

spring.liquibase.change-log: classpath:/db/changelog/db.changelog-master.xml

facebook:
  userAuthorizationUri: https://www.facebook.com/dialog/oauth
  accessTokenUri: https://graph.facebook.com/oauth/access_token
  userInfoUri: https://graph.facebook.com/me

vk:
  userAuthorizationUri: https://oauth.vk.com/authorize
  accessTokenUri: https://oauth.vk.com/access_token
  userInfoUri: https://api.vk.com/method/users.get
  apiVersion: 5.87

authentication.success.url.mobile: 'motive://'

springdoc.packagesToScan: 'org.motivepick'
springdoc.pathsToMatch: '/**'

# This is normally the origin of the Web app or * (if not Prod)
cors.allowedOriginPattern: '*'
