spring.datasource:
  url: jdbc:postgresql://localhost:5432/motive
  username: postgres
  password: postgres

facebook:
  clientId: 2126656117583758
  clientSecret: 16d922eb48ba0d30f0d9feee7c1acbec

authentication.success.url.web: http://localhost:3000/login-success/

jwt.token:
  issuer: motive-local
  signing.key: someVerySecureKey
