spring.datasource:
  url: ${POSTGRESQLCONNSTR_milestone}
  username: ${SPRING_DATASOURCE_USERNAME}
  password: ${SPRING_DATASOURCE_PASSWORD}

enforce.https.for.oauth: true

github:
  clientId: Ov23liyzNkFyK7z81NLq
  clientSecret: ${GITHUB_CLIENT_SECRET}

vk:
  clientId: 52094527
  clientSecret: ${VK_CLIENT_SECRET}

azure.openai:
  apiKey: ${AZURE_OPENAI_API_KEY}
  endpoint: ${AZURE_OPENAI_ENDPOINT}
  deploymentOrModelId: ${AZURE_OPENAI_DEPLOYMENT_MODEL_ID}

authentication.success.url.web: https://milestone.yaskovdev.com
logout.success.url: https://milestone.yaskovdev.com/login
cookie.domain: milestone.yaskovdev.com
cookie.secure: true

jwt.token:
  issuer: https://api.milestone.yaskovdev.com
  signing.key: ${JWT_TOKEN_SIGNING_KEY}

cors.allowedOriginPattern: 'https://milestone.yaskovdev.com'
