logging:
  level:
    com: DEBUG
    root: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

spring.data.mongodb.database: tasks

management.endpoints.web.exposure.include: info,health,httptrace
