spring.application.name: 'Milestone Back End'

spring.profiles.active: 'prod'

logging:
  level:
    com: INFO
    root: INFO
    springframework.security: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO

management.endpoints.web.exposure.include: info,health,httptrace

spring.jpa.show-sql: false
spring.jpa.properties.hibernate.format_sql: false

spring.liquibase.change-log: classpath:/db/changelog/db.changelog-master.xml

github:
  userAuthorizationUri: https://github.com/login/oauth/authorize
  accessTokenUri: https://github.com/login/oauth/access_token
  userInfoUri: https://api.github.com/user

vk:
  userAuthorizationUri: https://oauth.vk.com/authorize
  accessTokenUri: https://oauth.vk.com/access_token
  userInfoUri: https://api.vk.com/method/users.get
  apiVersion: 5.87

azure.openai:
  apiKey: ''
  endpoint: ''
  deploymentOrModelId: ''

authentication.success.url.mobile: 'motive://'
cookie.secure: false

springdoc.packagesToScan: 'org.motivepick'
springdoc.pathsToMatch: '/**'

# This is normally the origin of the Web app or * (if not Prod)
cors.allowedOriginPattern: '*'
