logging:
  level:
    com: INFO
    root: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

management.endpoints.web.exposure.include: info,health,httptrace

# Fixes Caused by: java.sql.SQLFeatureNotSupportedException:
# Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true

spring.liquibase.change-log: classpath:/db/changelog/db.changelog-master.xml

facebook:
  userAuthorizationUri: https://www.facebook.com/dialog/oauth
  accessTokenUri: https://graph.facebook.com/oauth/access_token
  userInfoUri: https://graph.facebook.com/me

vk:
  userAuthorizationUri: https://oauth.vk.com/authorize
  accessTokenUri: https://oauth.vk.com/access_token
  userInfoUri: https://api.vk.com/method/users.get
  apiVersion: 5.87

logging.level.org.springframework.security: DEBUG

authentication.success.url.mobile: 'motive://'
