logging:
  level:
    com: INFO
    root: INFO
    springframework.security: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

# TODO: remove the below section once PostgreSQL is configured
# SECTION STARTS

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

spring.jpa.show-sql: true
spring.jpa.properties.hibernate.format_sql: true

enforce.https.for.oauth: false

facebook:
  userAuthorizationUri: https://www.facebook.com/dialog/oauth
  accessTokenUri: https://graph.facebook.com/oauth/access_token
  userInfoUri: https://graph.facebook.com/me
  clientId: 2126656117583758
  clientSecret: 16d922eb48ba0d30f0d9feee7c1acbec

vk:
  userAuthorizationUri: https://oauth.vk.com/authorize
  accessTokenUri: https://oauth.vk.com/access_token
  userInfoUri: https://api.vk.com/method/users.get
  apiVersion: 5.87
  clientId: 6752973
  clientSecret: OIS0gHh6SiYYfx9MEhJk

authentication.success.url.web: http://localhost:3000
logout.success.url: http://localhost:3000/login
cookie.domain: localhost

jwt.token:
  issuer: motive-local
  signing.key: someVerySecureKey

# SECTION ENDS

management.endpoints.web.exposure.include: info,health,httptrace

# Fixes Caused by: java.sql.SQLFeatureNotSupportedException:
# Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true

spring.liquibase.change-log: classpath:/db/changelog/db.changelog-master.xml

# TODO: uncomment once PostgreSQL is configured
#facebook:
#  userAuthorizationUri: https://www.facebook.com/dialog/oauth
#  accessTokenUri: https://graph.facebook.com/oauth/access_token
#  userInfoUri: https://graph.facebook.com/me
#
#vk:
#  userAuthorizationUri: https://oauth.vk.com/authorize
#  accessTokenUri: https://oauth.vk.com/access_token
#  userInfoUri: https://api.vk.com/method/users.get
#  apiVersion: 5.87

authentication.success.url.mobile: 'motive://'
