spring.datasource:
  url: jdbc:postgresql://localhost:5432/motive
  username: postgres
  password: postgres

enforce.https.for.oauth: false

github:
  clientId: Ov23liyzNkFyK7z81NLq
  clientSecret: secret

vk:
  clientId: 6752973
  clientSecret: OIS0gHh6SiYYfx9MEhJk

authentication.success.url.web: http://localhost:3000
logout.success.url: http://localhost:3000/login
cookie.domain: localhost

jwt.token:
  issuer: http://localhost:8080
  signing.key: someVerySecureKey
